// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import "fmt"

const (
	keyProduce                     = 0
	keyFetch                       = 1
	keyListOffset                  = 2
	keyMetadata                    = 3
	keyLeaderAndIsr                = 4
	keyStopReplica                 = 5
	keyUpdateMetadata              = 6
	keyControlledShutdown          = 7
	keyOffsetCommit                = 8
	keyOffsetFetch                 = 9
	keyFindCoordinator             = 10
	keyJoinGroup                   = 11
	keyHeartbeat                   = 12
	keyLeaveGroup                  = 13
	keySyncGroup                   = 14
	keyDescribeGroups              = 15
	keyListGroups                  = 16
	keySaslHandshake               = 17
	keyApiVersions                 = 18
	keyCreateTopics                = 19
	keyDeleteTopics                = 20
	keyDeleteRecords               = 21
	keyInitProducerId              = 22
	keyOffsetForLeaderEpoch        = 23
	keyAddPartitionsToTxn          = 24
	keyAddOffsetsToTxn             = 25
	keyEndTxn                      = 26
	keyWriteTxnMarkers             = 27
	keyTxnOffsetCommit             = 28
	keyDescribeAcls                = 29
	keyCreateAcls                  = 30
	keyDeleteAcls                  = 31
	keyDescribeConfigs             = 32
	keyAlterConfigs                = 33
	keyAlterReplicaLogDirs         = 34
	keyDescribeLogDirs             = 35
	keySaslAuthenticate            = 36
	keyCreatePartitions            = 37
	keyCreateDelegationToken       = 38
	keyRenewDelegationToken        = 39
	keyExpireDelegationToken       = 40
	keyDescribeDelegationToken     = 41
	keyDeleteGroups                = 42
	keyElectLeaders                = 43
	keyIncrementalAlterConfigs     = 44
	keyAlterPartitionReassignments = 45
	keyListPartitionReassignments  = 46
	keyOffsetDelete                = 47
)

// apiVersion contains the negotiated versions for each api key
type apiVersion struct {
	Produce                     int16
	Fetch                       int16
	ListOffset                  int16
	Metadata                    int16
	LeaderAndIsr                int16
	StopReplica                 int16
	UpdateMetadata              int16
	ControlledShutdown          int16
	OffsetCommit                int16
	OffsetFetch                 int16
	FindCoordinator             int16
	JoinGroup                   int16
	Heartbeat                   int16
	LeaveGroup                  int16
	SyncGroup                   int16
	DescribeGroups              int16
	ListGroups                  int16
	SaslHandshake               int16
	ApiVersions                 int16
	CreateTopics                int16
	DeleteTopics                int16
	DeleteRecords               int16
	InitProducerId              int16
	OffsetForLeaderEpoch        int16
	AddPartitionsToTxn          int16
	AddOffsetsToTxn             int16
	EndTxn                      int16
	WriteTxnMarkers             int16
	TxnOffsetCommit             int16
	DescribeAcls                int16
	CreateAcls                  int16
	DeleteAcls                  int16
	DescribeConfigs             int16
	AlterConfigs                int16
	AlterReplicaLogDirs         int16
	DescribeLogDirs             int16
	SaslAuthenticate            int16
	CreatePartitions            int16
	CreateDelegationToken       int16
	RenewDelegationToken        int16
	ExpireDelegationToken       int16
	DescribeDelegationToken     int16
	DeleteGroups                int16
	ElectLeaders                int16
	IncrementalAlterConfigs     int16
	AlterPartitionReassignments int16
	ListPartitionReassignments  int16
	OffsetDelete                int16
}

// negotiateApiVersions accepts the apiKeys from the broker and negotiates
// acceptable versions for each api based on the versions supported by
// this library.
func negotiateApiVersions(apiKeys []ApiVersionsResponseKey18) (apiVersion, error) {
	// Since this file is generated, there's no need to externalize the supported
	// versions elsewhere.  We can simply inline the values into the call to matchVersion
	var av apiVersion
	var err error
	for _, apiKey := range apiKeys {
		switch apiKey.ApiKey {
		case keyProduce:
			av.Produce, err = matchVersion(apiKey, 0, 8)
			if err != nil {
				return apiVersion{}, err
			}
		case keyFetch:
			av.Fetch, err = matchVersion(apiKey, 0, 11)
			if err != nil {
				return apiVersion{}, err
			}
		case keyListOffset:
			av.ListOffset, err = matchVersion(apiKey, 0, 5)
			if err != nil {
				return apiVersion{}, err
			}
		case keyMetadata:
			av.Metadata, err = matchVersion(apiKey, 0, 9)
			if err != nil {
				return apiVersion{}, err
			}
		case keyLeaderAndIsr:
			av.LeaderAndIsr, err = matchVersion(apiKey, 0, 4)
			if err != nil {
				return apiVersion{}, err
			}
		case keyStopReplica:
			av.StopReplica, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyUpdateMetadata:
			av.UpdateMetadata, err = matchVersion(apiKey, 0, 6)
			if err != nil {
				return apiVersion{}, err
			}
		case keyControlledShutdown:
			av.ControlledShutdown, err = matchVersion(apiKey, 0, 3)
			if err != nil {
				return apiVersion{}, err
			}
		case keyOffsetCommit:
			av.OffsetCommit, err = matchVersion(apiKey, 0, 8)
			if err != nil {
				return apiVersion{}, err
			}
		case keyOffsetFetch:
			av.OffsetFetch, err = matchVersion(apiKey, 0, 6)
			if err != nil {
				return apiVersion{}, err
			}
		case keyFindCoordinator:
			av.FindCoordinator, err = matchVersion(apiKey, 0, 3)
			if err != nil {
				return apiVersion{}, err
			}
		case keyJoinGroup:
			av.JoinGroup, err = matchVersion(apiKey, 0, 6)
			if err != nil {
				return apiVersion{}, err
			}
		case keyHeartbeat:
			av.Heartbeat, err = matchVersion(apiKey, 0, 4)
			if err != nil {
				return apiVersion{}, err
			}
		case keyLeaveGroup:
			av.LeaveGroup, err = matchVersion(apiKey, 0, 4)
			if err != nil {
				return apiVersion{}, err
			}
		case keySyncGroup:
			av.SyncGroup, err = matchVersion(apiKey, 0, 4)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDescribeGroups:
			av.DescribeGroups, err = matchVersion(apiKey, 0, 5)
			if err != nil {
				return apiVersion{}, err
			}
		case keyListGroups:
			av.ListGroups, err = matchVersion(apiKey, 0, 3)
			if err != nil {
				return apiVersion{}, err
			}
		case keySaslHandshake:
			av.SaslHandshake, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyApiVersions:
			av.ApiVersions, err = matchVersion(apiKey, 0, 3)
			if err != nil {
				return apiVersion{}, err
			}
		case keyCreateTopics:
			av.CreateTopics, err = matchVersion(apiKey, 0, 5)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDeleteTopics:
			av.DeleteTopics, err = matchVersion(apiKey, 0, 4)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDeleteRecords:
			av.DeleteRecords, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyInitProducerId:
			av.InitProducerId, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyOffsetForLeaderEpoch:
			av.OffsetForLeaderEpoch, err = matchVersion(apiKey, 0, 3)
			if err != nil {
				return apiVersion{}, err
			}
		case keyAddPartitionsToTxn:
			av.AddPartitionsToTxn, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyAddOffsetsToTxn:
			av.AddOffsetsToTxn, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyEndTxn:
			av.EndTxn, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyWriteTxnMarkers:
			av.WriteTxnMarkers, err = matchVersion(apiKey, 0, 0)
			if err != nil {
				return apiVersion{}, err
			}
		case keyTxnOffsetCommit:
			av.TxnOffsetCommit, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDescribeAcls:
			av.DescribeAcls, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyCreateAcls:
			av.CreateAcls, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDeleteAcls:
			av.DeleteAcls, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDescribeConfigs:
			av.DescribeConfigs, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyAlterConfigs:
			av.AlterConfigs, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyAlterReplicaLogDirs:
			av.AlterReplicaLogDirs, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDescribeLogDirs:
			av.DescribeLogDirs, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keySaslAuthenticate:
			av.SaslAuthenticate, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyCreatePartitions:
			av.CreatePartitions, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyCreateDelegationToken:
			av.CreateDelegationToken, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyRenewDelegationToken:
			av.RenewDelegationToken, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyExpireDelegationToken:
			av.ExpireDelegationToken, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDescribeDelegationToken:
			av.DescribeDelegationToken, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyDeleteGroups:
			av.DeleteGroups, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyElectLeaders:
			av.ElectLeaders, err = matchVersion(apiKey, 0, 2)
			if err != nil {
				return apiVersion{}, err
			}
		case keyIncrementalAlterConfigs:
			av.IncrementalAlterConfigs, err = matchVersion(apiKey, 0, 1)
			if err != nil {
				return apiVersion{}, err
			}
		case keyAlterPartitionReassignments:
			av.AlterPartitionReassignments, err = matchVersion(apiKey, 0, 0)
			if err != nil {
				return apiVersion{}, err
			}
		case keyListPartitionReassignments:
			av.ListPartitionReassignments, err = matchVersion(apiKey, 0, 0)
			if err != nil {
				return apiVersion{}, err
			}
		case keyOffsetDelete:
			av.OffsetDelete, err = matchVersion(apiKey, 0, 0)
			if err != nil {
				return apiVersion{}, err
			}
		}
	}
	return av, nil
}

// matchVersion determines which version of the api to use
func matchVersion(apiKey ApiVersionsResponseKey18, minVersion, maxVersion int16) (int16, error) {
	for version := apiKey.MaxVersion; version >= apiKey.MinVersion; version-- {
		if version := apiKey.MaxVersion; version >= minVersion && version <= maxVersion {
			return version, nil
		}
	}
	return 0, fmt.Errorf("unable to negotiate version for api key, %v", apiKey.ApiKey)
}
