// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// SyncGroupResponse; ApiKey: 14, Versions: 0-4
type SyncGroupResponse struct {
	ThrottleTimeMs int32  // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 1+
	ErrorCode      int16  // The error code, or 0 if there was no error. Versions: 0+
	Assignment     []byte // The member assignment. Versions: 0+
}

// size of SyncGroupResponse; Versions: 0-4
func (t SyncGroupResponse) size(version int16) int32 {
	var sz int32
	if version >= 1 {
		sz += sizeof.Int32 // ThrottleTimeMs
	}
	sz += sizeof.Int16               // ErrorCode
	sz += sizeof.Bytes(t.Assignment) // Assignment
	return sz
}

// encode SyncGroupResponse; Versions: 0-4
func (t SyncGroupResponse) Encode(e *protocol.Encoder, version int16) {
	if version >= 1 {
		e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	}
	e.PutInt16(t.ErrorCode)  // ErrorCode
	e.PutBytes(t.Assignment) // Assignment
}

// decode SyncGroupResponse; Versions: 0-4
func (t *SyncGroupResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	if version >= 1 {
		t.ThrottleTimeMs, err = d.Int32()
		if err != nil {
			return err
		}
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	t.Assignment, err = d.Bytes()
	if err != nil {
		return err
	}
	return err
}
