// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// CreateAclsResponse; ApiKey: 30, Versions: 0-1
type CreateAclsResponse struct {
	ThrottleTimeMs int32                  // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 0+
	Results        []CreatableAclResult30 // The results for each ACL creation. Versions: 0+
}

// size of CreateAclsResponse; Versions: 0-1
func (t CreateAclsResponse) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32       // ThrottleTimeMs
	sz += sizeof.ArrayLength // Results
	for i := len(t.Results) - 1; i >= 0; i-- {
		sz += t.Results[i].size(version)
	}
	return sz
}

// encode CreateAclsResponse; Versions: 0-1
func (t CreateAclsResponse) encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	// Results
	len1 := len(t.Results)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Results[i].encode(e, version)
	}
}

// decode CreateAclsResponse; Versions: 0-1
func (t *CreateAclsResponse) decode(d *protocol.Decoder, version int16) error {
	var err error
	t.ThrottleTimeMs, err = d.Int32()
	if err != nil {
		return err
	}
	// Results
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Results = make([]CreatableAclResult30, n)
		for i := 0; i < n; i++ {
			var item CreatableAclResult30
			if err := (&item).decode(d, version); err != nil {
				return err
			}
			t.Results[i] = item
		}
	}
	return err
}

type CreatableAclResult30 struct {
	ErrorCode    int16  // The result error, or zero if there was no error. Versions: 0+
	ErrorMessage string // The result message, or null if there was no error. Versions: 0+
}

// size of CreatableAclResult30; Versions: 0-1
func (t CreatableAclResult30) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int16                  // ErrorCode
	sz += sizeof.String(t.ErrorMessage) // ErrorMessage
	return sz
}

// encode CreatableAclResult30; Versions: 0-1
func (t CreatableAclResult30) encode(e *protocol.Encoder, version int16) {
	e.PutInt16(t.ErrorCode)     // ErrorCode
	e.PutString(t.ErrorMessage) // ErrorMessage
}

// decode CreatableAclResult30; Versions: 0-1
func (t *CreatableAclResult30) decode(d *protocol.Decoder, version int16) error {
	var err error
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	t.ErrorMessage, err = d.String()
	if err != nil {
		return err
	}
	return err
}
