// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// LeaderAndIsrResponse; ApiKey: 4, Versions: 0-4
type LeaderAndIsrResponse struct {
	ErrorCode       int16                         // The error code, or 0 if there was no error. Versions: 0+
	PartitionErrors []LeaderAndIsrPartitionError4 // Each partition. Versions: 0+
}

// size of LeaderAndIsrResponse; Versions: 0-4
func (t LeaderAndIsrResponse) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int16       // ErrorCode
	sz += sizeof.ArrayLength // PartitionErrors
	for i := len(t.PartitionErrors) - 1; i >= 0; i-- {
		sz += t.PartitionErrors[i].size(version)
	}
	return sz
}

// encode LeaderAndIsrResponse; Versions: 0-4
func (t LeaderAndIsrResponse) Encode(e *protocol.Encoder, version int16) {
	e.PutInt16(t.ErrorCode) // ErrorCode
	// PartitionErrors
	len1 := len(t.PartitionErrors)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.PartitionErrors[i].Encode(e, version)
	}
}

// decode LeaderAndIsrResponse; Versions: 0-4
func (t *LeaderAndIsrResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	// PartitionErrors
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.PartitionErrors = make([]LeaderAndIsrPartitionError4, n)
		for i := 0; i < n; i++ {
			var item LeaderAndIsrPartitionError4
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.PartitionErrors[i] = item
		}
	}
	return err
}

type LeaderAndIsrPartitionError4 struct {
	TopicName      string // The topic name. Versions: 0+
	PartitionIndex int32  // The partition index. Versions: 0+
	ErrorCode      int16  // The partition error code, or 0 if there was no error. Versions: 0+
}

// size of LeaderAndIsrPartitionError4; Versions: 0-4
func (t LeaderAndIsrPartitionError4) size(version int16) int32 {
	var sz int32
	sz += sizeof.String(t.TopicName) // TopicName
	sz += sizeof.Int32               // PartitionIndex
	sz += sizeof.Int16               // ErrorCode
	return sz
}

// encode LeaderAndIsrPartitionError4; Versions: 0-4
func (t LeaderAndIsrPartitionError4) Encode(e *protocol.Encoder, version int16) {
	e.PutString(t.TopicName)     // TopicName
	e.PutInt32(t.PartitionIndex) // PartitionIndex
	e.PutInt16(t.ErrorCode)      // ErrorCode
}

// decode LeaderAndIsrPartitionError4; Versions: 0-4
func (t *LeaderAndIsrPartitionError4) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.TopicName, err = d.String()
	if err != nil {
		return err
	}
	t.PartitionIndex, err = d.Int32()
	if err != nil {
		return err
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	return err
}
