// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
)

// ListGroupsRequest; ApiKey: 16, Versions: 0-3
type ListGroupsRequest struct {
}

// size of ListGroupsRequest; Versions: 0-3
func (t ListGroupsRequest) size(version int16) int32 {
	var sz int32
	return sz
}

// encode ListGroupsRequest; Versions: 0-3
func (t ListGroupsRequest) Encode(e *protocol.Encoder, version int16) {
}

// decode ListGroupsRequest; Versions: 0-3
func (t *ListGroupsRequest) Decode(d *protocol.Decoder, version int16) error {
	var err error
	return err
}
