// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// DeleteGroupsResponse; ApiKey: 42, Versions: 0-2
type DeleteGroupsResponse struct {
	ThrottleTimeMs int32                    // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 0+
	Results        []DeletableGroupResult42 // The deletion results Versions: 0+
}

// size of DeleteGroupsResponse; Versions: 0-2
func (t DeleteGroupsResponse) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32       // ThrottleTimeMs
	sz += sizeof.ArrayLength // Results
	for i := len(t.Results) - 1; i >= 0; i-- {
		sz += t.Results[i].size(version)
	}
	return sz
}

// encode DeleteGroupsResponse; Versions: 0-2
func (t DeleteGroupsResponse) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	// Results
	len1 := len(t.Results)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Results[i].Encode(e, version)
	}
}

// decode DeleteGroupsResponse; Versions: 0-2
func (t *DeleteGroupsResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.ThrottleTimeMs, err = d.Int32()
	if err != nil {
		return err
	}
	// Results
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Results = make([]DeletableGroupResult42, n)
		for i := 0; i < n; i++ {
			var item DeletableGroupResult42
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Results[i] = item
		}
	}
	return err
}

type DeletableGroupResult42 struct {
	GroupId   string // The group id Versions: 0+
	ErrorCode int16  // The deletion error, or 0 if the deletion succeeded. Versions: 0+
}

// size of DeletableGroupResult42; Versions: 0-2
func (t DeletableGroupResult42) size(version int16) int32 {
	var sz int32
	sz += sizeof.String(t.GroupId) // GroupId
	sz += sizeof.Int16             // ErrorCode
	return sz
}

// encode DeletableGroupResult42; Versions: 0-2
func (t DeletableGroupResult42) Encode(e *protocol.Encoder, version int16) {
	e.PutString(t.GroupId)  // GroupId
	e.PutInt16(t.ErrorCode) // ErrorCode
}

// decode DeletableGroupResult42; Versions: 0-2
func (t *DeletableGroupResult42) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.GroupId, err = d.String()
	if err != nil {
		return err
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	return err
}
