// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// DeleteTopicsRequest; ApiKey: 20, Versions: 0-4
type DeleteTopicsRequest struct {
	TopicNames []string // The names of the topics to delete Versions: 0+
	TimeoutMs  int32    // The length of time in milliseconds to wait for the deletions to complete. Versions: 0+
}

// size of DeleteTopicsRequest; Versions: 0-4
func (t DeleteTopicsRequest) Size(version int16) int32 {
	var sz int32
	sz += sizeof.StringArray(t.TopicNames) // TopicNames
	sz += sizeof.Int32                     // TimeoutMs
	return sz
}

// encode DeleteTopicsRequest; Versions: 0-4
func (t DeleteTopicsRequest) Encode(e *protocol.Encoder, version int16) {
	e.PutStringArray(t.TopicNames) // TopicNames
	e.PutInt32(t.TimeoutMs)        // TimeoutMs
}

// decode DeleteTopicsRequest; Versions: 0-4
func (t *DeleteTopicsRequest) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.TopicNames, err = d.StringArray()
	if err != nil {
		return err
	}
	t.TimeoutMs, err = d.Int32()
	if err != nil {
		return err
	}
	return err
}
