// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// AlterReplicaLogDirsResponse; ApiKey: 34, Versions: 0-1
type AlterReplicaLogDirsResponse struct {
	ThrottleTimeMs int32                             // Duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 0+
	Results        []AlterReplicaLogDirTopicResult34 // The results for each topic. Versions: 0+
}

// size of AlterReplicaLogDirsResponse; Versions: 0-1
func (t AlterReplicaLogDirsResponse) Size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32       // ThrottleTimeMs
	sz += sizeof.ArrayLength // Results
	for i := len(t.Results) - 1; i >= 0; i-- {
		sz += t.Results[i].Size(version)
	}
	return sz
}

// encode AlterReplicaLogDirsResponse; Versions: 0-1
func (t AlterReplicaLogDirsResponse) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	// Results
	len1 := len(t.Results)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Results[i].Encode(e, version)
	}
}

// decode AlterReplicaLogDirsResponse; Versions: 0-1
func (t *AlterReplicaLogDirsResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.ThrottleTimeMs, err = d.Int32()
	if err != nil {
		return err
	}
	// Results
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Results = make([]AlterReplicaLogDirTopicResult34, n)
		for i := 0; i < n; i++ {
			var item AlterReplicaLogDirTopicResult34
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Results[i] = item
		}
	}
	return err
}

type AlterReplicaLogDirTopicResult34 struct {
	TopicName  string                                // The name of the topic. Versions: 0+
	Partitions []AlterReplicaLogDirPartitionResult34 // The results for each partition. Versions: 0+
}

// size of AlterReplicaLogDirTopicResult34; Versions: 0-1
func (t AlterReplicaLogDirTopicResult34) Size(version int16) int32 {
	var sz int32
	sz += sizeof.String(t.TopicName) // TopicName
	sz += sizeof.ArrayLength         // Partitions
	for i := len(t.Partitions) - 1; i >= 0; i-- {
		sz += t.Partitions[i].Size(version)
	}
	return sz
}

// encode AlterReplicaLogDirTopicResult34; Versions: 0-1
func (t AlterReplicaLogDirTopicResult34) Encode(e *protocol.Encoder, version int16) {
	e.PutString(t.TopicName) // TopicName
	// Partitions
	len1 := len(t.Partitions)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Partitions[i].Encode(e, version)
	}
}

// decode AlterReplicaLogDirTopicResult34; Versions: 0-1
func (t *AlterReplicaLogDirTopicResult34) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.TopicName, err = d.String()
	if err != nil {
		return err
	}
	// Partitions
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Partitions = make([]AlterReplicaLogDirPartitionResult34, n)
		for i := 0; i < n; i++ {
			var item AlterReplicaLogDirPartitionResult34
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Partitions[i] = item
		}
	}
	return err
}

type AlterReplicaLogDirPartitionResult34 struct {
	PartitionIndex int32 // The partition index. Versions: 0+
	ErrorCode      int16 // The error code, or 0 if there was no error. Versions: 0+
}

// size of AlterReplicaLogDirPartitionResult34; Versions: 0-1
func (t AlterReplicaLogDirPartitionResult34) Size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32 // PartitionIndex
	sz += sizeof.Int16 // ErrorCode
	return sz
}

// encode AlterReplicaLogDirPartitionResult34; Versions: 0-1
func (t AlterReplicaLogDirPartitionResult34) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.PartitionIndex) // PartitionIndex
	e.PutInt16(t.ErrorCode)      // ErrorCode
}

// decode AlterReplicaLogDirPartitionResult34; Versions: 0-1
func (t *AlterReplicaLogDirPartitionResult34) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.PartitionIndex, err = d.Int32()
	if err != nil {
		return err
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	return err
}
