// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// ResponseHeader; ApiKey: 0, Versions: 0-1
type ResponseHeader struct {
	CorrelationId int32 // The correlation ID of this response. Versions: 0+
}

// size of ResponseHeader; Versions: 0-1
func (t ResponseHeader) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32 // CorrelationId
	return sz
}

// encode ResponseHeader; Versions: 0-1
func (t ResponseHeader) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.CorrelationId) // CorrelationId
}

// decode ResponseHeader; Versions: 0-1
func (t *ResponseHeader) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.CorrelationId, err = d.Int32()
	if err != nil {
		return err
	}
	return err
}
