// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// DeleteGroupsRequest; ApiKey: 42, Versions: 0-2
type DeleteGroupsRequest struct {
	GroupsNames []string // The group names to delete. Versions: 0+
}

// size of DeleteGroupsRequest; Versions: 0-2
func (t DeleteGroupsRequest) size(version int16) int32 {
	var sz int32
	sz += sizeof.StringArray(t.GroupsNames) // GroupsNames
	return sz
}

// encode DeleteGroupsRequest; Versions: 0-2
func (t DeleteGroupsRequest) encode(e *protocol.Encoder, version int16) {
	e.PutStringArray(t.GroupsNames) // GroupsNames
}

// decode DeleteGroupsRequest; Versions: 0-2
func (t *DeleteGroupsRequest) decode(d *protocol.Decoder, version int16) error {
	var err error
	t.GroupsNames, err = d.StringArray()
	if err != nil {
		return err
	}
	return err
}
