// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// CreatePartitionsResponse; ApiKey: 37, Versions: 0-1
type CreatePartitionsResponse struct {
	ThrottleTimeMs int32                           // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 0+
	Results        []CreatePartitionsTopicResult37 // The partition creation results for each topic. Versions: 0+
}

// size of CreatePartitionsResponse; Versions: 0-1
func (t CreatePartitionsResponse) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32       // ThrottleTimeMs
	sz += sizeof.ArrayLength // Results
	for i := len(t.Results) - 1; i >= 0; i-- {
		sz += t.Results[i].size(version)
	}
	return sz
}

// encode CreatePartitionsResponse; Versions: 0-1
func (t CreatePartitionsResponse) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	// Results
	len1 := len(t.Results)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Results[i].Encode(e, version)
	}
}

// decode CreatePartitionsResponse; Versions: 0-1
func (t *CreatePartitionsResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.ThrottleTimeMs, err = d.Int32()
	if err != nil {
		return err
	}
	// Results
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Results = make([]CreatePartitionsTopicResult37, n)
		for i := 0; i < n; i++ {
			var item CreatePartitionsTopicResult37
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Results[i] = item
		}
	}
	return err
}

type CreatePartitionsTopicResult37 struct {
	Name         string // The topic name. Versions: 0+
	ErrorCode    int16  // The result error, or zero if there was no error. Versions: 0+
	ErrorMessage string // The result message, or null if there was no error. Versions: 0+
}

// size of CreatePartitionsTopicResult37; Versions: 0-1
func (t CreatePartitionsTopicResult37) size(version int16) int32 {
	var sz int32
	sz += sizeof.String(t.Name)         // Name
	sz += sizeof.Int16                  // ErrorCode
	sz += sizeof.String(t.ErrorMessage) // ErrorMessage
	return sz
}

// encode CreatePartitionsTopicResult37; Versions: 0-1
func (t CreatePartitionsTopicResult37) Encode(e *protocol.Encoder, version int16) {
	e.PutString(t.Name)         // Name
	e.PutInt16(t.ErrorCode)     // ErrorCode
	e.PutString(t.ErrorMessage) // ErrorMessage
}

// decode CreatePartitionsTopicResult37; Versions: 0-1
func (t *CreatePartitionsTopicResult37) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.Name, err = d.String()
	if err != nil {
		return err
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	t.ErrorMessage, err = d.String()
	if err != nil {
		return err
	}
	return err
}
