// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// FindCoordinatorResponse; ApiKey: 10, Versions: 0-3
type FindCoordinatorResponse struct {
	ThrottleTimeMs int32  // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 1+
	ErrorCode      int16  // The error code, or 0 if there was no error. Versions: 0+
	ErrorMessage   string // The error message, or null if there was no error. Versions: 1+
	NodeId         int32  // The node id. Versions: 0+
	Host           string // The host name. Versions: 0+
	Port           int32  // The port. Versions: 0+
}

// size of FindCoordinatorResponse; Versions: 0-3
func (t FindCoordinatorResponse) size(version int16) int32 {
	var sz int32
	if version >= 1 {
		sz += sizeof.Int32 // ThrottleTimeMs
	}
	sz += sizeof.Int16 // ErrorCode
	if version >= 1 {
		sz += sizeof.String(t.ErrorMessage) // ErrorMessage
	}
	sz += sizeof.Int32          // NodeId
	sz += sizeof.String(t.Host) // Host
	sz += sizeof.Int32          // Port
	return sz
}

// encode FindCoordinatorResponse; Versions: 0-3
func (t FindCoordinatorResponse) Encode(e *protocol.Encoder, version int16) {
	if version >= 1 {
		e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	}
	e.PutInt16(t.ErrorCode) // ErrorCode
	if version >= 1 {
		e.PutString(t.ErrorMessage) // ErrorMessage
	}
	e.PutInt32(t.NodeId) // NodeId
	e.PutString(t.Host)  // Host
	e.PutInt32(t.Port)   // Port
}

// decode FindCoordinatorResponse; Versions: 0-3
func (t *FindCoordinatorResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	if version >= 1 {
		t.ThrottleTimeMs, err = d.Int32()
		if err != nil {
			return err
		}
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	if version >= 1 {
		t.ErrorMessage, err = d.String()
		if err != nil {
			return err
		}
	}
	t.NodeId, err = d.Int32()
	if err != nil {
		return err
	}
	t.Host, err = d.String()
	if err != nil {
		return err
	}
	t.Port, err = d.Int32()
	if err != nil {
		return err
	}
	return err
}
