// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// DescribeGroupsRequest; ApiKey: 15, Versions: 0-5
type DescribeGroupsRequest struct {
	Groups                      []string // The names of the groups to describe Versions: 0+
	IncludeAuthorizedOperations bool     // Whether to include authorized operations. Versions: 3+
}

// size of DescribeGroupsRequest; Versions: 0-5
func (t DescribeGroupsRequest) size(version int16) int32 {
	var sz int32
	sz += sizeof.StringArray(t.Groups) // Groups
	if version >= 3 {
		sz += sizeof.Bool // IncludeAuthorizedOperations
	}
	return sz
}

// encode DescribeGroupsRequest; Versions: 0-5
func (t DescribeGroupsRequest) Encode(e *protocol.Encoder, version int16) {
	e.PutStringArray(t.Groups) // Groups
	if version >= 3 {
		e.PutBool(t.IncludeAuthorizedOperations) // IncludeAuthorizedOperations
	}
}

// decode DescribeGroupsRequest; Versions: 0-5
func (t *DescribeGroupsRequest) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.Groups, err = d.StringArray()
	if err != nil {
		return err
	}
	if version >= 3 {
		t.IncludeAuthorizedOperations, err = d.Bool()
		if err != nil {
			return err
		}
	}
	return err
}
