// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// ListOffsetResponse; ApiKey: 2, Versions: 0-5
type ListOffsetResponse struct {
	ThrottleTimeMs int32                      // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. Versions: 2+
	Topics         []ListOffsetTopicResponse2 // Each topic in the response. Versions: 0+
}

// size of ListOffsetResponse; Versions: 0-5
func (t ListOffsetResponse) size(version int16) int32 {
	var sz int32
	if version >= 2 {
		sz += sizeof.Int32 // ThrottleTimeMs
	}
	sz += sizeof.ArrayLength // Topics
	for i := len(t.Topics) - 1; i >= 0; i-- {
		sz += t.Topics[i].size(version)
	}
	return sz
}

// encode ListOffsetResponse; Versions: 0-5
func (t ListOffsetResponse) Encode(e *protocol.Encoder, version int16) {
	if version >= 2 {
		e.PutInt32(t.ThrottleTimeMs) // ThrottleTimeMs
	}
	// Topics
	len1 := len(t.Topics)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Topics[i].Encode(e, version)
	}
}

// decode ListOffsetResponse; Versions: 0-5
func (t *ListOffsetResponse) Decode(d *protocol.Decoder, version int16) error {
	var err error
	if version >= 2 {
		t.ThrottleTimeMs, err = d.Int32()
		if err != nil {
			return err
		}
	}
	// Topics
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Topics = make([]ListOffsetTopicResponse2, n)
		for i := 0; i < n; i++ {
			var item ListOffsetTopicResponse2
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Topics[i] = item
		}
	}
	return err
}

type ListOffsetTopicResponse2 struct {
	Name       string                         // The topic name Versions: 0+
	Partitions []ListOffsetPartitionResponse2 // Each partition in the response. Versions: 0+
}

// size of ListOffsetTopicResponse2; Versions: 0-5
func (t ListOffsetTopicResponse2) size(version int16) int32 {
	var sz int32
	sz += sizeof.String(t.Name) // Name
	sz += sizeof.ArrayLength    // Partitions
	for i := len(t.Partitions) - 1; i >= 0; i-- {
		sz += t.Partitions[i].size(version)
	}
	return sz
}

// encode ListOffsetTopicResponse2; Versions: 0-5
func (t ListOffsetTopicResponse2) Encode(e *protocol.Encoder, version int16) {
	e.PutString(t.Name) // Name
	// Partitions
	len1 := len(t.Partitions)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Partitions[i].Encode(e, version)
	}
}

// decode ListOffsetTopicResponse2; Versions: 0-5
func (t *ListOffsetTopicResponse2) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.Name, err = d.String()
	if err != nil {
		return err
	}
	// Partitions
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Partitions = make([]ListOffsetPartitionResponse2, n)
		for i := 0; i < n; i++ {
			var item ListOffsetPartitionResponse2
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Partitions[i] = item
		}
	}
	return err
}

type ListOffsetPartitionResponse2 struct {
	PartitionIndex  int32   // The partition index. Versions: 0+
	ErrorCode       int16   // The partition error code, or 0 if there was no error. Versions: 0+
	OldStyleOffsets []int64 // The result offsets. Versions: 0-0
	Timestamp       int64   // The timestamp associated with the returned offset. Versions: 1+
	Offset          int64   // The returned offset. Versions: 1+
	LeaderEpoch     int32   // Versions: 4+
}

// size of ListOffsetPartitionResponse2; Versions: 0-5
func (t ListOffsetPartitionResponse2) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32 // PartitionIndex
	sz += sizeof.Int16 // ErrorCode
	if version >= 0 && version <= 0 {
		sz += sizeof.Int64Array(t.OldStyleOffsets) // OldStyleOffsets
	}
	if version >= 1 {
		sz += sizeof.Int64 // Timestamp
	}
	if version >= 1 {
		sz += sizeof.Int64 // Offset
	}
	if version >= 4 {
		sz += sizeof.Int32 // LeaderEpoch
	}
	return sz
}

// encode ListOffsetPartitionResponse2; Versions: 0-5
func (t ListOffsetPartitionResponse2) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.PartitionIndex) // PartitionIndex
	e.PutInt16(t.ErrorCode)      // ErrorCode
	if version >= 0 && version <= 0 {
		e.PutInt64Array(t.OldStyleOffsets) // OldStyleOffsets
	}
	if version >= 1 {
		e.PutInt64(t.Timestamp) // Timestamp
	}
	if version >= 1 {
		e.PutInt64(t.Offset) // Offset
	}
	if version >= 4 {
		e.PutInt32(t.LeaderEpoch) // LeaderEpoch
	}
}

// decode ListOffsetPartitionResponse2; Versions: 0-5
func (t *ListOffsetPartitionResponse2) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.PartitionIndex, err = d.Int32()
	if err != nil {
		return err
	}
	t.ErrorCode, err = d.Int16()
	if err != nil {
		return err
	}
	if version >= 0 && version <= 0 {
		t.OldStyleOffsets, err = d.Int64Array()
		if err != nil {
			return err
		}
	}
	if version >= 1 {
		t.Timestamp, err = d.Int64()
		if err != nil {
			return err
		}
	}
	if version >= 1 {
		t.Offset, err = d.Int64()
		if err != nil {
			return err
		}
	}
	if version >= 4 {
		t.LeaderEpoch, err = d.Int32()
		if err != nil {
			return err
		}
	}
	return err
}
