// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// ListPartitionReassignmentsRequest; ApiKey: 46, Versions: 0
type ListPartitionReassignmentsRequest struct {
	TimeoutMs int32                                // The time in ms to wait for the request to complete. Versions: 0+
	Topics    []ListPartitionReassignmentsTopics46 // The topics to list partition reassignments for, or null to list everything. Versions: 0+
}

// size of ListPartitionReassignmentsRequest; Versions: 0
func (t ListPartitionReassignmentsRequest) size(version int16) int32 {
	var sz int32
	sz += sizeof.Int32       // TimeoutMs
	sz += sizeof.ArrayLength // Topics
	for i := len(t.Topics) - 1; i >= 0; i-- {
		sz += t.Topics[i].size(version)
	}
	return sz
}

// encode ListPartitionReassignmentsRequest; Versions: 0
func (t ListPartitionReassignmentsRequest) Encode(e *protocol.Encoder, version int16) {
	e.PutInt32(t.TimeoutMs) // TimeoutMs
	// Topics
	len1 := len(t.Topics)
	e.PutArrayLength(len1)
	for i := 0; i < len1; i++ {
		t.Topics[i].Encode(e, version)
	}
}

// decode ListPartitionReassignmentsRequest; Versions: 0
func (t *ListPartitionReassignmentsRequest) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.TimeoutMs, err = d.Int32()
	if err != nil {
		return err
	}
	// Topics
	if n, err := d.ArrayLength(); err != nil {
		return err
	} else if n >= 0 {
		t.Topics = make([]ListPartitionReassignmentsTopics46, n)
		for i := 0; i < n; i++ {
			var item ListPartitionReassignmentsTopics46
			if err := (&item).Decode(d, version); err != nil {
				return err
			}
			t.Topics[i] = item
		}
	}
	return err
}

type ListPartitionReassignmentsTopics46 struct {
	Name             string  // The topic name Versions: 0+
	PartitionIndexes []int32 // The partitions to list partition reassignments for. Versions: 0+
}

// size of ListPartitionReassignmentsTopics46; Versions: 0
func (t ListPartitionReassignmentsTopics46) size(version int16) int32 {
	var sz int32
	sz += sizeof.String(t.Name)                 // Name
	sz += sizeof.Int32Array(t.PartitionIndexes) // PartitionIndexes
	return sz
}

// encode ListPartitionReassignmentsTopics46; Versions: 0
func (t ListPartitionReassignmentsTopics46) Encode(e *protocol.Encoder, version int16) {
	e.PutString(t.Name)                 // Name
	e.PutInt32Array(t.PartitionIndexes) // PartitionIndexes
}

// decode ListPartitionReassignmentsTopics46; Versions: 0
func (t *ListPartitionReassignmentsTopics46) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.Name, err = d.String()
	if err != nil {
		return err
	}
	t.PartitionIndexes, err = d.Int32Array()
	if err != nil {
		return err
	}
	return err
}
