// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kafka

import (
	"github.com/savaki/kafka/protocol"
	"github.com/savaki/kafka/sizeof"
)

// ExpireDelegationTokenRequest; ApiKey: 40, Versions: 0-1
type ExpireDelegationTokenRequest struct {
	Hmac               []byte // The HMAC of the delegation token to be expired. Versions: 0+
	ExpiryTimePeriodMs int64  // The expiry time period in milliseconds. Versions: 0+
}

// size of ExpireDelegationTokenRequest; Versions: 0-1
func (t ExpireDelegationTokenRequest) Size(version int16) int32 {
	var sz int32
	sz += sizeof.Bytes(t.Hmac) // Hmac
	sz += sizeof.Int64         // ExpiryTimePeriodMs
	return sz
}

// encode ExpireDelegationTokenRequest; Versions: 0-1
func (t ExpireDelegationTokenRequest) Encode(e *protocol.Encoder, version int16) {
	e.PutBytes(t.Hmac)               // Hmac
	e.PutInt64(t.ExpiryTimePeriodMs) // ExpiryTimePeriodMs
}

// decode ExpireDelegationTokenRequest; Versions: 0-1
func (t *ExpireDelegationTokenRequest) Decode(d *protocol.Decoder, version int16) error {
	var err error
	t.Hmac, err = d.Bytes()
	if err != nil {
		return err
	}
	t.ExpiryTimePeriodMs, err = d.Int64()
	if err != nil {
		return err
	}
	return err
}
