// Code generated by kafka-protocol-gen. DO NOT EDIT.
//
// Copyright 2019 Matt Ho
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package message

const (
	KeyProduce                     = 0
	KeyFetch                       = 1
	KeyListOffset                  = 2
	KeyMetadata                    = 3
	KeyLeaderAndIsr                = 4
	KeyStopReplica                 = 5
	KeyUpdateMetadata              = 6
	KeyControlledShutdown          = 7
	KeyOffsetCommit                = 8
	KeyOffsetFetch                 = 9
	KeyFindCoordinator             = 10
	KeyJoinGroup                   = 11
	KeyHeartbeat                   = 12
	KeyLeaveGroup                  = 13
	KeySyncGroup                   = 14
	KeyDescribeGroups              = 15
	KeyListGroups                  = 16
	KeySaslHandshake               = 17
	KeyApiVersions                 = 18
	KeyCreateTopics                = 19
	KeyDeleteTopics                = 20
	KeyDeleteRecords               = 21
	KeyInitProducerId              = 22
	KeyOffsetForLeaderEpoch        = 23
	KeyAddPartitionsToTxn          = 24
	KeyAddOffsetsToTxn             = 25
	KeyEndTxn                      = 26
	KeyWriteTxnMarkers             = 27
	KeyTxnOffsetCommit             = 28
	KeyDescribeAcls                = 29
	KeyCreateAcls                  = 30
	KeyDeleteAcls                  = 31
	KeyDescribeConfigs             = 32
	KeyAlterConfigs                = 33
	KeyAlterReplicaLogDirs         = 34
	KeyDescribeLogDirs             = 35
	KeySaslAuthenticate            = 36
	KeyCreatePartitions            = 37
	KeyCreateDelegationToken       = 38
	KeyRenewDelegationToken        = 39
	KeyExpireDelegationToken       = 40
	KeyDescribeDelegationToken     = 41
	KeyDeleteGroups                = 42
	KeyElectLeaders                = 43
	KeyIncrementalAlterConfigs     = 44
	KeyAlterPartitionReassignments = 45
	KeyListPartitionReassignments  = 46
	KeyOffsetDelete                = 47
)
