name: Build and Test

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Echo
        run: echo "${{ matrix.os }} ${{ matrix.node }}"
      - name: Test
        if: matrix.os != 'windows-latest'
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Test - Windows
        if: matrix.os == 'windows-latest'
        run: go test -race ./...
      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)